news/news/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.contrib.sitemaps.views import sitemap
from RSS_and_SITEMAP.sitemap import NewsSitemap, StaticSitemap
# import debug_toolbar


schema_view = get_schema_view(
   openapi.Info(
      title="Library API",
      default_version='v1',
      description="online library",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="admin@mail.ru"),
      license=openapi.License(name=""),
   ),
   public=True,
   permission_classes=(permissions.AllowAny, ),
)


sitemaps = {  # список составляющих карты сайта
    'static': StaticSitemap,
    'news': NewsSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_news_board.urls')),
    path('users/', include('app_users.urls')),
    path('blog/', include('app_blog.urls')),

    path('api/', include('API_data.urls')),

    path('rss/', include('RSS_and_SITEMAP.urls')),  # лента новостей
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),  # карта сайта
    path('i18n/', include('django.conf.urls.i18n')),  # интернационализация
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema_swagger_ui'),  # спецификации API и методов
    path('oauth', include('social_django.urls', namespace='social')),
    path('blog_life/', include('blog_life.urls')),  # приложение для симуляции жизни в блоге

    # path('__debug__/', include(debug_toolbar.urls))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/app_news_board/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class News(models.Model):
    """Модель новости"""

    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, verbose_name=_('author'))
    title = models.CharField(max_length=1500, db_index=True, default=None, blank=True, null=True, verbose_name=_('title'))  # используется только при симуляции жизни
    content = models.CharField(max_length=1500, default='', verbose_name=_('content'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_('updated_at'))
    views_count = models.IntegerField(default=0, verbose_name=_('views_count'))
    is_active = models.BooleanField(default=True, verbose_name=_('is_active'))

    likes = models.ManyToManyField(User, related_name='likes', blank=True, verbose_name=_('likes'))
    saves = models.ManyToManyField(User, related_name='saves', blank=True, verbose_name=_('saves'))

    def get_absolute_url(self):
        """Метод для корректной работы карты сайта"""
        return reverse('news_detail', args=[str(self.id)])

    class Meta:
        verbose_name_plural = _('news')
        verbose_name = _('new')
        ordering = ['-id']

    def increment_view_count(self):
        """Увеличивает количество просмотрев новости на 1"""
        self.views_count += 1
        self.save()

    def total_likes(self):
        """Возвращает количество лайков"""
        return self.likes.all().count()


class Images(models.Model):
    """Модель изображений для новости"""

    news = models.ForeignKey(News, default=None, on_delete=models.CASCADE, verbose_name=_('news'))
    image = models.ImageField(upload_to='images/', null=True, blank=True, verbose_name=_('image'))

    class Meta:
        verbose_name_plural = _('images')
        verbose_name = _('image')


class Comment(models.Model):
    """Модель комментария"""

    news = models.ForeignKey(News, on_delete=models.CASCADE, blank=True, null=True, related_name='comment_news', verbose_name=_('new'))
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, verbose_name=_('user'))
    text = models.CharField(max_length=1500, default=None, null=True, verbose_name=_('text'))
    image = models.ImageField(upload_to='images/comment_images/', null=True, blank=True, verbose_name=_('image'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_('updated_at'))

    class Meta:
        verbose_name_plural = _('comments')
        verbose_name = _('comment')

news/templates/news/comment_delete.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block title %}
    Delete comment
{% endblock %}




{% block menu %}
    <b>{% trans 'Delete' %}</b>
{% endblock %}




{% block content %}

<div class="board">
    <form method="POST">
        {% csrf_token %}
        <p>{% trans 'Are you sure' %}?</p>
        <button class="button">{% trans 'Yes' %}</button>
    </form>
</div>

{% endblock %}

news/templates/news/create.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block title %}
    Create post
{% endblock %}





{% block menu %}
    <b>{% trans 'Create' %}</b>
{% endblock %}




{% block content %}

<div class="board">
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.title.as_hidden }}
        {{ form.author.as_hidden }}
        {{ form.views_count.as_hidden }}

        <p><b>{% trans 'Content' %}</b><br>
        {{ form.content }}</p>

        <p><b><label class="form-control-label" for="images">{% trans 'Images' %}</label></b><br>
        <input class="form-control-file" type="file" name="images" id="note-image" placeholder="" multiple>
        <button id="remove-file" type="button"> ✖ </button></p>

        {% if is_moderator %}
            <p>is active: {{ form.is_active }}</p>
            <br>
        {% else %}
            {{ form.is_active.as_hidden }}
        {% endif %}
        <button class="add_news" type="submit">{% trans 'Make post' %}</button>
    </form>
</div>




<script>
    document.getElementById('remove-file').onclick = function() {
        var file = document.getElementById("note-image");
        file.value = file.defaultValue;
    }
</script>

{% endblock %}

news/templates/news/delete.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block title %}
    Delete post
{% endblock %}




{% block menu %}
    <b>{% trans 'Delete' %}</b>
{% endblock %}




{% block content %}

<div class="board">
    <form method="POST">
        {% csrf_token %}
        <p>{% trans 'Are you sure' %}?</p>
        <button class="button">{% trans 'Yes' %}</button>
    </form>
</div>

{% endblock %}

news/templates/news/edit.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block title %}
    Edit post
{% endblock %}




{% block menu %}
    <b>{% trans 'Edit' %}</b>
{% endblock %}




{% block content %}

<div class="board">
        <form method="post" action="">
            {% csrf_token %}
            <p><b>{% trans 'Content' %}</b></p>
            <p>{{ news_form.content }}</p>
            {{ news_form.views_count.as_hidden }}
            {% if is_moderator %}
                <p>{% trans 'is active' %}: {{ news_form.is_active }}</p>
            {% else %}
                {{ news_form.is_active.as_hidden }}
            {% endif %}
            <br>
            <button class="add_news" type="submit">{% trans 'Save' %}</button>
        </form>
</div>

{% endblock %}

news/templates/news/need_moderation.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block title %}
    Suspicious posts
{% endblock %}



{% block menu %}
    <b>{% trans 'Need to moderate' %}</b>
{% endblock %}



{% block content %}
    {{ all_posts }}
{% endblock %}

news/templates/news/news_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block title %}
    Post
{% endblock %}




{% block menu %}
    <b>{% trans 'Post' %}</b>
{% endblock %}



{% block content %}

<div class="board">
    <div class="news_container">
        <div>
            <div class="news_author_info">
                <a href="{% url 'user_blog' pk=news.author.id %}">{{ post.author }}</a>,
                {{ post.created_at }}
                {% if post.created_at|date:"M d, Y" != post.updated_at|date:"M d, Y" %}
                    {% trans 'Edit' %}: {{ post.updated_at }}
                {% endif %}
            </div>

            <div class="news_action">
                <div class="dropdown_post">
                    <img class="news_info_img" src="{% static 'img/option.png'%}">
                    <div class="dropdown_post_content">
                        <a href=".">{% trans 'report' %}</a>
                        {% if post.author == request.user or is_moderator == True %}
                            <a href="{% url 'post_edit' profile_id=post.id %}">{% trans 'edit' %}</a>
                            <a href="{% url 'post_delete' pk=post.id %}">{% trans 'delete' %}</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="news_content">
            <p>{{ post.content }}</p>

            <div class="news_img_block">
                {% for image in post.images_set.all %}

                        <a href="#{{ image.image }}"><img class="news_img" title="" src="../media/{{ image.image }}" alt="" /></a>


                        <a href="#x" class="overlay" id="{{ image.image }}"></a>


                        <div class="popup">
                            <img class="is-news_img" src="../media/{{ image.image }}" alt="" />
                            <a class="close" title="Закрыть" href="#close"></a>
                        </div>

                        <div class="caption">
                            <h3>
                            <a href="#"></a>
                            </h3>
                        </div>

                {% empty %}
                {% endfor %}
            </div>

        </div>

        <div class="news_list_info">
            <div class="like-section">
                {% include 'functions/like_section.html' %}
            </div>


            <div class="view-section">
                <img class="news_list_info_img" src="{% static 'img/views.png' %}">{{ post.views_count }}
            </div>
            <div class="comment-section">
                <img class="news_list_info_img" src="{% static 'img/comments.png' %}">{{ post.comment_news.all.count }}
            </div>
            {% if post.images_set.all %}
                <div class="images-section">
                    <img class="news_list_info_img" src="{% static 'img/news_list_img_info.png' %}">{{ post.images_set.count }}
                </div>
            {% endif %}


            <div class="save-section">
                {% include 'functions/save_section.html' %}
            </div>

        </div>
    </div>

    <br>
    <div class="comments_list">
        <h3>{% trans 'Comments' %}</h3>
        {% for comment in post.comment_news.all %}
            <div class="comment_author_block">
                <a class="comment_author" href="{% url 'user_blog' pk=comment.user.id %}">
                  <img class="comment_author_img" src="{{ comment.user.profile.profile_img.url }}">{{ comment.user }}
                </a>
                {{ comment.created_at|date:"M d, Y" }}

                <div class="news_action">
                    <div class="dropdown_post">
                        <img class="news_info_img" src="{% static 'img/option.png'%}">
                        <div class="dropdown_post_content">
                            <a href=".">{% trans 'report' %}</a>
                            {% if comment.user == request.user or is_moderator == True %}
                                <a href="{% url 'comment_delete' pk=comment.id %}">{% trans 'delete' %}</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

            <div class="comment_content_block">
               {{ comment.text }}
                <br>
               {% if comment.image %}
                    <img class="comment_img" src="../media/{{ comment.image }}"/>
                {% endif %}
            </div>
            <br>
        {% empty %}
            {% trans 'There are no comments yet, be the first' %}
        {% endfor %}
    </div>










    <div class="comments_block">

        <div class="main_user_name">{% trans 'Add comment' %} ↑</div>

        <div class="dropdown-content_comment">
            <div class="comments_block">

                {% if request.user.is_authenticated %}
                    <form action="." method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.text }}<br>
                        {{ form.image }}
                        <button id="remove-file" type="button"> ✖ </button></p>
                        <input class='comment_button' type="submit">
                    </form>
                {% else %}
                    <a href="{% url 'login' %}">{% trans "Login" %}</a> {% trans 'to leave a comment' %}</p>
                {% endif %}
            </div>
        </div>
    </div>

</div>


<script>
    document.getElementById('remove-file').onclick = function() {
        var file = document.getElementById("comment-img");
        file.value = file.defaultValue;
    }
</script>


{% endblock %}

news/templates/news/news_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block title %}
    Explore
{% endblock %}




{% block menu %}
    <b>{% trans 'Explore' %}</b>

{% endblock %}



{% block content %}

<div class="board">
    <div class="news_list">
        <ul>
            {% for post in all_news %}
                <li>
                    <div class="news_author_img_block">
                        <a href="{% url 'user_blog' pk=post.author.id %}">
                            <img class="news_author_img" src="{{ post.author.profile.profile_img.url }}">
                        </a>
                    </div>
                    <div class="news_author_content_block">
                        <a class="news_author" href="{% url 'user_blog' pk=post.author.id %}">{{ post.author }}</a>

                        {{ post.created_at|date:"M d, Y" }}

                        {% if post.created_at|date:"M d, Y" != post.updated_at|date:"M d, Y" %}
                            {% trans "Edit:" %} {{ post.updated_at|date:"M d, Y" }}
                        {% endif %}
                        <br>

                        <div class="news_text_block">
                            <a class="news_text" href="{% url 'news_detail' pk=post.id %}">{{ post.content|truncatechars:150 }}</a>

                            <div class="news_list_img_block">
                                {% for image in post.images_set.all %}
                                    <div class="list_img_inline" >
                                        <a href="#{{ image.image }}"><img class="news_list_img" title="" src="../media/{{ image.image }}" alt="" /></a>


                                        <a href="#x" class="overlay" id="{{ image.image }}"></a>


                                        <div class="popup">
                                            <img class="is-news_img" src="../media/{{ image.image }}" alt="" />
                                            <a class="close" title="Закрыть" href="#close"></a>
                                        </div>

                                        <div class="caption">
                                            <h3>
                                            <a href="#"></a>
                                            </h3>
                                        </div>
                                    </div>

                                {% empty %}
                                {% endfor %}
                            </div>

                        </div>


                        <div class="news_list_info">
                            <div class="like-section">
                                {% include 'functions/like_section.html' %}
                            </div>


                            <div class="view-section">
                                <img class="news_list_info_img" src="{% static 'img/views.png' %}">{{ post.views_count }}
                            </div>
                            <div class="comment-section">
                                <a style="font-weight: normal; opacity: 0.9;" href="{% url 'news_detail' pk=post.id %}">
                                <img class="news_list_info_img" src="{% static 'img/comments.png' %}">{{ post.comment_news.all.count }}
                                </a>
                            </div>
                            {% if post.images_set.all %}
                                <div class="images-section">
                                    <img class="news_list_info_img" src="{% static 'img/news_list_img_info.png' %}">{{ post.images_set.count }}
                                </div>
                            {% endif %}


                            <div class="save-section">
                                {% include 'functions/save_section.html' %}
                            </div>

                        </div>
                    </div>
                </li>
                <br>
            {% empty %}
            {% endfor %}
        </ul>
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

</div>

{% endblock %}